[
  {
    "discussion_id": "374733161",
    "pr_number": 6118,
    "pr_file": "packages/driver/src/cypress/error_messages.coffee",
    "created_at": "2020-02-04T15:17:40+00:00",
    "commented_code": "Before the page load, you were bound to the origin policy:\n         > #{originPolicy}\n \n-      A cross origin error happens when your application navigates to a new superdomain which does not match the origin policy above.\n+      A cross origin error happens when your application navigates to a new domain which does not match the origin policy above.",
    "repo_full_name": "cypress-io/cypress",
    "discussion_comments": [
      {
        "comment_id": "374733161",
        "repo_full_name": "cypress-io/cypress",
        "pr_number": 6118,
        "pr_file": "packages/driver/src/cypress/error_messages.coffee",
        "discussion_id": "374733161",
        "commented_code": "@@ -615,15 +615,15 @@ module.exports = {\n       Before the page load, you were bound to the origin policy:\n         > #{originPolicy}\n \n-      A cross origin error happens when your application navigates to a new superdomain which does not match the origin policy above.\n+      A cross origin error happens when your application navigates to a new domain which does not match the origin policy above.",
        "comment_created_at": "2020-02-04T15:17:40+00:00",
        "comment_author": "flotwig",
        "comment_body": "```suggestion\r\n      A cross origin error happens when your application navigates to a new URL which does not match the origin policy above.\r\n```\r\n\r\nsince it's not necessarily the domain that's changed",
        "pr_file_module": null
      },
      {
        "comment_id": "374735544",
        "repo_full_name": "cypress-io/cypress",
        "pr_number": 6118,
        "pr_file": "packages/driver/src/cypress/error_messages.coffee",
        "discussion_id": "374733161",
        "commented_code": "@@ -615,15 +615,15 @@ module.exports = {\n       Before the page load, you were bound to the origin policy:\n         > #{originPolicy}\n \n-      A cross origin error happens when your application navigates to a new superdomain which does not match the origin policy above.\n+      A cross origin error happens when your application navigates to a new domain which does not match the origin policy above.",
        "comment_created_at": "2020-02-04T15:20:50+00:00",
        "comment_author": "jennifer-shehane",
        "comment_body": "True story",
        "pr_file_module": null
      }
    ]
  },
  {
    "discussion_id": "374733758",
    "pr_number": 6118,
    "pr_file": "packages/driver/src/cypress/error_messages.coffee",
    "created_at": "2020-02-04T15:18:22+00:00",
    "commented_code": "URL from the `url` parameter: {{url}}\n     \"\"\"\n     cannot_visit_2nd_domain: \"\"\"\n-      #{cmd('visit')} failed because you are attempting to visit a second unique domain.\n+      #{cmd('visit')} failed because you are attempting to visit a domain that is of a different origin.",
    "repo_full_name": "cypress-io/cypress",
    "discussion_comments": [
      {
        "comment_id": "374733758",
        "repo_full_name": "cypress-io/cypress",
        "pr_number": 6118,
        "pr_file": "packages/driver/src/cypress/error_messages.coffee",
        "discussion_id": "374733758",
        "commented_code": "@@ -1060,19 +1060,17 @@ module.exports = {\n       URL from the `url` parameter: {{url}}\n     \"\"\"\n     cannot_visit_2nd_domain: \"\"\"\n-      #{cmd('visit')} failed because you are attempting to visit a second unique domain.\n+      #{cmd('visit')} failed because you are attempting to visit a domain that is of a different origin.",
        "comment_created_at": "2020-02-04T15:18:22+00:00",
        "comment_author": "flotwig",
        "comment_body": "```suggestion\r\n      #{cmd('visit')} failed because you are attempting to visit a URL that is of a different origin.\r\n```",
        "pr_file_module": null
      }
    ]
  },
  {
    "discussion_id": "380808445",
    "pr_number": 6118,
    "pr_file": "packages/driver/src/cypress/error_messages.coffee",
    "created_at": "2020-02-18T17:02:55+00:00",
    "commented_code": "URL from the `options` object: {{optionsUrl}}\n       URL from the `url` parameter: {{url}}\n     \"\"\"\n-    cannot_visit_2nd_domain: \"\"\"\n-      #{cmd('visit')} failed because you are attempting to visit a second unique domain.\n+    cannot_visit_different_protocol: \"\"\"\n+      #{cmd('visit')} failed because you are attempting to visit a URL that is of a different origin.\n+\n+      The new URL is considered different origin because the 'protocol' is different.\n+\n+      You may only 'cy.visit()' same origin URLs within a single test.\n+\n+      The previous domain you visited was: '{{previousDomain}}'\n+\n+      You're attempting to visit this URL: '{{attemptedDomain}}'\n+\n+      You may need to restructure some of your test code to avoid this problem.\n+\n+      https://on.cypress.io/cannot-visit-different-origin-domain\n+    \"\"\"\n+    cannot_visit_different_port: \"\"\"\n+      #{cmd('visit')} failed because you are attempting to visit a URL that is of a different origin.\n \n-      You may only visit a single unique domain per test.\n+      The new URL is considered different origin because the 'port' is different.",
    "repo_full_name": "cypress-io/cypress",
    "discussion_comments": [
      {
        "comment_id": "380808445",
        "repo_full_name": "cypress-io/cypress",
        "pr_number": 6118,
        "pr_file": "packages/driver/src/cypress/error_messages.coffee",
        "discussion_id": "380808445",
        "commented_code": "@@ -1074,20 +1071,50 @@ module.exports = {\n       URL from the `options` object: {{optionsUrl}}\n       URL from the `url` parameter: {{url}}\n     \"\"\"\n-    cannot_visit_2nd_domain: \"\"\"\n-      #{cmd('visit')} failed because you are attempting to visit a second unique domain.\n+    cannot_visit_different_protocol: \"\"\"\n+      #{cmd('visit')} failed because you are attempting to visit a URL that is of a different origin.\n+\n+      The new URL is considered different origin because the 'protocol' is different.\n+\n+      You may only 'cy.visit()' same origin URLs within a single test.\n+\n+      The previous domain you visited was: '{{previousDomain}}'\n+\n+      You're attempting to visit this URL: '{{attemptedDomain}}'\n+\n+      You may need to restructure some of your test code to avoid this problem.\n+\n+      https://on.cypress.io/cannot-visit-different-origin-domain\n+    \"\"\"\n+    cannot_visit_different_port: \"\"\"\n+      #{cmd('visit')} failed because you are attempting to visit a URL that is of a different origin.\n \n-      You may only visit a single unique domain per test.\n+      The new URL is considered different origin because the 'port' is different.",
        "comment_created_at": "2020-02-18T17:02:55+00:00",
        "comment_author": "flotwig",
        "comment_body": "```suggestion\r\n      The new URL is considered a different origin because the port is different.\r\n```",
        "pr_file_module": null
      },
      {
        "comment_id": "380809000",
        "repo_full_name": "cypress-io/cypress",
        "pr_number": 6118,
        "pr_file": "packages/driver/src/cypress/error_messages.coffee",
        "discussion_id": "380808445",
        "commented_code": "@@ -1074,20 +1071,50 @@ module.exports = {\n       URL from the `options` object: {{optionsUrl}}\n       URL from the `url` parameter: {{url}}\n     \"\"\"\n-    cannot_visit_2nd_domain: \"\"\"\n-      #{cmd('visit')} failed because you are attempting to visit a second unique domain.\n+    cannot_visit_different_protocol: \"\"\"\n+      #{cmd('visit')} failed because you are attempting to visit a URL that is of a different origin.\n+\n+      The new URL is considered different origin because the 'protocol' is different.\n+\n+      You may only 'cy.visit()' same origin URLs within a single test.\n+\n+      The previous domain you visited was: '{{previousDomain}}'\n+\n+      You're attempting to visit this URL: '{{attemptedDomain}}'\n+\n+      You may need to restructure some of your test code to avoid this problem.\n+\n+      https://on.cypress.io/cannot-visit-different-origin-domain\n+    \"\"\"\n+    cannot_visit_different_port: \"\"\"\n+      #{cmd('visit')} failed because you are attempting to visit a URL that is of a different origin.\n \n-      You may only visit a single unique domain per test.\n+      The new URL is considered different origin because the 'port' is different.",
        "comment_created_at": "2020-02-18T17:03:49+00:00",
        "comment_author": "flotwig",
        "comment_body": "I know that \"different origin\" is supposed to be read with the same inflection as \"same-origin\", but it doesn't really read like that to me, what do you think about \"a different origin\" instead?",
        "pr_file_module": null
      }
    ]
  },
  {
    "discussion_id": "380837336",
    "pr_number": 6118,
    "pr_file": "packages/driver/src/cypress/error_messages.coffee",
    "created_at": "2020-02-18T17:54:10+00:00",
    "commented_code": "URL from the `options` object: {{optionsUrl}}\n       URL from the `url` parameter: {{url}}\n     \"\"\"\n-    cannot_visit_2nd_domain: \"\"\"\n-      #{cmd('visit')} failed because you are attempting to visit a second unique domain.\n+    cannot_visit_different_origin: \"\"\"\n+      #{cmd('visit')} failed because you are attempting to visit a URL that is of a different origin.\n \n-      You may only visit a single unique domain per test.\n+      The new URL is considered a different origin because the following parts of the URL are different: {{differences}}\n \n-      Different subdomains are okay, but unique domains are not.\n+      You may only #{cmd('visit')} same origin URLs within a single test.",
    "repo_full_name": "cypress-io/cypress",
    "discussion_comments": [
      {
        "comment_id": "380837336",
        "repo_full_name": "cypress-io/cypress",
        "pr_number": 6118,
        "pr_file": "packages/driver/src/cypress/error_messages.coffee",
        "discussion_id": "380837336",
        "commented_code": "@@ -1074,20 +1071,20 @@ module.exports = {\n       URL from the `options` object: {{optionsUrl}}\n       URL from the `url` parameter: {{url}}\n     \"\"\"\n-    cannot_visit_2nd_domain: \"\"\"\n-      #{cmd('visit')} failed because you are attempting to visit a second unique domain.\n+    cannot_visit_different_origin: \"\"\"\n+      #{cmd('visit')} failed because you are attempting to visit a URL that is of a different origin.\n \n-      You may only visit a single unique domain per test.\n+      The new URL is considered a different origin because the following parts of the URL are different: {{differences}}\n \n-      Different subdomains are okay, but unique domains are not.\n+      You may only #{cmd('visit')} same origin URLs within a single test.",
        "comment_created_at": "2020-02-18T17:54:10+00:00",
        "comment_author": "flotwig",
        "comment_body": "```suggestion\r\n      You may only #{cmd('visit')} same-origin URLs within a single test.\r\n```",
        "pr_file_module": null
      }
    ]
  }
]